### PR TITLE
shorten link text to avoid wrapping issue on mobile

### PR DESCRIPTION
**Pull request by scottleibrand**

### CODE REVIEW

**Comment by danamlewis** [comment]
I don't think my changes to the high level /index.html are getting copied into site/index.html... I already changed this on the main page?

**Comment by danamlewis** [comment]
see https://github.com/Co-Epi/website/commit/62b8c34298426587454fb468601477659cd6eac8

**Comment by scottleibrand** [comment]
Updated with your language as a workaround for now.

**Comment by scottleibrand** [comment]
I'm seeing the language on the site without merging this, so not sure whether this is needed.

**Pull request closed without merging**
